#!/bin/sh
# Verwendet die externalpipe von st, um eine Rofi-Auswahl kürzlich verwendeter Befehle anzuzeigen
# und dem Benutzer zu ermöglichen, die Ausgabe eines Befehls zu kopieren.
# xclip wird für dieses Skript benötigt.
# Von Jaywalker und Luke

# Menü-Befehl definieren (Zentrale Stelle für einfache Anpassungen)
rofi_menu() {
	rofi -dmenu -i -location 0 -theme-str 'window { width: 90%; } listview { lines: 10; }' "$@"
}

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | rofi_menu -p "Ausgabe welches Befehls kopieren?" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
