#!/bin/sh

# Menü-Befehl definieren (Zentrale Stelle für einfache Anpassungen)
rofi_menu() {
	rofi -dmenu -i -location 0 -theme-str 'window { width: 90%; } listview { lines: 10; }' "$@"
}

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' | # Zuerst Zeilenumbrüche und mutt-Seitenleisten entfernen:
	grep -aEo "$urlregex" | # Nur URLs wie oben definiert herausfiltern.
	uniq | # Benachbarte Duplikate ignorieren.
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")" # xdg-open erkennt keine URLs ohne http

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
	h) printf "Optionale Argumente für benutzerdefinierte Verwendung:\\n  -c: kopieren\\n  -o: xdg-open\\n  -h: Diese Nachricht anzeigen\\n" && exit 1 ;;
	o) chosen="$(echo "$urls" | rofi_menu -p 'Folge welcher Url?')"
	setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
	c) echo "$urls" | rofi_menu -p 'Kopiere welche Url?' | tr -d '\n' | xclip -selection clipboard ;;
	*) printf "Ungültige Option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done
